package com.aidoctor.diagnosis.runtime.u06.wait;
import com.aidoctor.diagnosis.runtime.foundation.RuntimeThreadWaitTransitionService;import com.aidoctor.diagnosis.runtime.foundation.RuntimeWaitCheckpointService;import com.aidoctor.diagnosis.runtime.u06.U06Ids;
public final class U06WaitCoordinator{
 private final RuntimeWaitCheckpointService checkpoints;private final RuntimeThreadWaitTransitionService threads;
 public U06WaitCoordinator(RuntimeWaitCheckpointService c,RuntimeThreadWaitTransitionService t){if(c==null||t==null)throw new IllegalArgumentException("services required");checkpoints=c;threads=t;}
 public Result establish(Command c){checkpoints.initialize(c.threadId,c.consultationId,c.createdAt);RuntimeWaitCheckpointService.Reservation r=checkpoints.reserve(new RuntimeWaitCheckpointService.Command(c.checkpointId,c.consultationId,c.threadId,c.runId,c.questionId,c.pendingQuestionRef,c.selectionEffectId,c.deliveryEffectId,c.parentWaitEffectId,c.deliveryId,c.confirmationRef,c.clinicalStateVersion,c.consultationWaitEffectId,c.dependencyBindingRef,c.questionPolicyRef,c.checkpointFingerprint,c.createdAt));threads.enterAwaitingUser(c.threadId,c.runId,c.checkpointId,c.parentWaitEffectId);return new Result(c.checkpointId,U06Ids.hash("u07elig",c.parentWaitEffectId,c.checkpointId,"1"),r.replay);}
 public static final class Command{public final String checkpointId,consultationId,threadId,runId,questionId,pendingQuestionRef,selectionEffectId,deliveryEffectId,parentWaitEffectId,deliveryId,confirmationRef,consultationWaitEffectId,dependencyBindingRef,questionPolicyRef,checkpointFingerprint,createdAt;public final int clinicalStateVersion;
  public Command(String cp,String c,String t,String r,String q,String pending,String sel,String delEffect,String parent,String delivery,String confirm,int version,String consultWait,String dep,String policy,String fp,String at){checkpointId=req(cp);consultationId=req(c);threadId=req(t);runId=req(r);questionId=req(q);pendingQuestionRef=req(pending);selectionEffectId=req(sel);deliveryEffectId=req(delEffect);parentWaitEffectId=req(parent);deliveryId=req(delivery);confirmationRef=req(confirm);clinicalStateVersion=version;consultationWaitEffectId=req(consultWait);dependencyBindingRef=req(dep);questionPolicyRef=req(policy);checkpointFingerprint=req(fp);createdAt=req(at);}}
 public static final class Result{public final String checkpointId,eligibilityId;public final boolean replay;Result(String c,String e,boolean r){checkpointId=c;eligibilityId=e;replay=r;}}
 private static String req(String v){if(v==null||v.trim().isEmpty())throw new IllegalArgumentException("value required");return v.trim();}
}
