package com.aidoctor.diagnosis.runtime.u01;
import lombok.Getter;import lombok.NoArgsConstructor;import javax.persistence.*;import java.time.LocalDateTime;
@Entity @Table(name="clinical_consultation") @Getter @NoArgsConstructor
public class ConsultationRecord{
 public static final String ACTIVE="ACTIVE",WAITING_USER="WAITING_USER";
 @Id @Column(name="consultation_id",length=128,nullable=false)private String consultationId;@Version @Column(name="row_version",nullable=false)private Long rowVersion;@Column(name="cdp_id",length=128,nullable=false,unique=true)private String cdpId;@Column(name="user_id",length=128,nullable=false)private String userId;@Column(name="lifecycle_status",length=32,nullable=false)private String lifecycleStatus;@Column(name="current_wait_effect_id",length=128)private String currentWaitEffectId;@Column(name="subject_status",length=32,nullable=false)private String subjectStatus;@Column(name="subject_type",length=32)private String subjectType;@Column(name="subject_reference_id",length=128)private String subjectReferenceId;@Column(name="problem_status",length=32,nullable=false)private String problemStatus;@Column(name="problem_text",length=2000)private String problemText;@Column(name="scope_decision",length=32,nullable=false)private String scopeDecision;@Column(name="clarification_reason",length=128)private String clarificationReason;@Column(name="early_safety_signal",nullable=false)private boolean earlySafetySignal;@Column(name="start_event_id",length=128,nullable=false,unique=true)private String startEventId;@Column(name="created_at",nullable=false,updatable=false)private LocalDateTime createdAt;
 public ConsultationRecord(String consultationId,String cdpId,String userId,U01StartCommand command,U01SemanticDecision decision,LocalDateTime createdAt){this.consultationId=req(consultationId,"consultationId");rowVersion=0L;this.cdpId=req(cdpId,"cdpId");this.userId=req(userId,"userId");lifecycleStatus=ACTIVE;currentWaitEffectId=null;subjectStatus=req(decision.getSubjectStatus(),"subjectStatus");subjectType=decision.getNormalizedSubjectType();subjectReferenceId=trim(command.getSubjectReferenceId());problemStatus=req(decision.getProblemStatus(),"problemStatus");problemText=trim(command.getProblemText());scopeDecision=req(decision.getScopeDecision(),"scopeDecision");clarificationReason=decision.getClarificationReason();earlySafetySignal=decision.isEarlySafetySignalPresent();startEventId=req(command.getEventId(),"startEventId");this.createdAt=createdAt==null?LocalDateTime.now():createdAt;}
 public void enterWaitingUser(String effect){if(!ACTIVE.equals(lifecycleStatus)||currentWaitEffectId!=null)throw new IllegalStateException("Consultation not eligible for WAITING_USER");lifecycleStatus=WAITING_USER;currentWaitEffectId=req(effect,"waitEffectId");}
 private static String trim(String v){return v==null||v.trim().isEmpty()?null:v.trim();}private static String req(String v,String n){String x=trim(v);if(x==null)throw new IllegalArgumentException(n+" is required");return x;}
}
