package com.aidoctor.diagnosis.runtime.foundation;
import lombok.Getter;import lombok.NoArgsConstructor;import javax.persistence.*;import java.time.LocalDateTime;
@Entity @Table(name="clinical_runtime_wait_checkpoint") @Getter @NoArgsConstructor
public class RuntimeWaitCheckpointRecord{
 @Id @Column(name="checkpoint_id",length=128,nullable=false)private String checkpointId;@Column(name="consultation_id",length=128,nullable=false)private String consultationId;@Column(name="thread_id",length=128,nullable=false)private String threadId;@Column(name="run_id",length=128,nullable=false)private String runId;@Column(name="question_id",length=128,nullable=false)private String questionId;@Column(name="pending_question_ref",length=256,nullable=false)private String pendingQuestionRef;
 @Column(name="question_selection_effect_id",length=128,nullable=false)private String questionSelectionEffectId;@Column(name="question_delivery_effect_id",length=128,nullable=false)private String questionDeliveryEffectId;@Column(name="question_delivered_wait_effect_id",length=128,nullable=false,unique=true)private String questionDeliveredWaitEffectId;@Column(name="delivery_id",length=128,nullable=false)private String deliveryId;@Column(name="delivery_confirmation_ref",length=128,nullable=false)private String deliveryConfirmationRef;
 @Column(name="clinical_state_version",nullable=false)private Integer clinicalStateVersion;@Column(name="consultation_wait_effect_id",length=128,nullable=false)private String consultationWaitEffectId;@Column(name="dependency_binding_ref",length=128)private String dependencyBindingRef;@Column(name="question_policy_ref",length=128)private String questionPolicyRef;@Column(name="payload_fingerprint",length=128,nullable=false)private String payloadFingerprint;@Column(name="checkpoint_status",length=32,nullable=false)private String checkpointStatus;@Column(name="created_at",nullable=false)private LocalDateTime createdAt;
 public RuntimeWaitCheckpointRecord(String cp,String c,String t,String r,String q,String pending,String sel,String del,String parent,String delivery,String confirm,int version,String consultWait,String dep,String policy,String fp,LocalDateTime now){checkpointId=req(cp);consultationId=req(c);threadId=req(t);runId=req(r);questionId=req(q);pendingQuestionRef=req(pending);questionSelectionEffectId=req(sel);questionDeliveryEffectId=req(del);questionDeliveredWaitEffectId=req(parent);deliveryId=req(delivery);deliveryConfirmationRef=req(confirm);clinicalStateVersion=Integer.valueOf(version);consultationWaitEffectId=req(consultWait);dependencyBindingRef=dep;questionPolicyRef=policy;payloadFingerprint=req(fp);checkpointStatus="ACTIVE";createdAt=now==null?LocalDateTime.now():now;}
 public boolean same(String fp,String run,String effect){return payloadFingerprint.equals(fp)&&runId.equals(run)&&questionDeliveredWaitEffectId.equals(effect);}private static String req(String v){if(v==null||v.trim().isEmpty())throw new IllegalArgumentException("value required");return v.trim();}
}
